# Source: https://alacritty.org/config-alacritty.html

# General
live_config_reload = true
working_directory = "None" # Inherit from parent

[shell]
program = "wsl"

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 1.0

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.25

[selection]
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  # https://github.com/alacritty/alacritty/issues/1108
  { key = "Key6", mods = "Control", chars = "\u001e" },
]

[debug]
# render_timer = false
# persistent_logging = false
# log_level = "Debug"
# renderer = "None"
# print_events = true
# highlight_damage = false
# prefer_egl = false
